[project]
name = "tapi"
version = "0.1.0"
description = "TEE Oracle based on UV"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dstack-sdk==0.1.2",
    "asyncio>=3.4.3",
    "fastapi==0.111.0"
]
