name: Test Solidity Contracts

on:
  push:
    branches:
      - main
    paths:
      - 'contracts/**'
      - '.github/workflows/contracts-test.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'contracts/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Foundry version info
        run: |
          forge --version
          cast --version
          anvil --version

      - name: Install dependencies
        run: forge install

      - name: Build contracts
        run: forge build

      - name: Run tests
        run: forge test -vvv 